import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/components/NavBar";
import HeaderNav from "@/components/Helper/HeaderNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex">
          {/* Sidebar Navigation (Hidden on Mobile, Visible on Large Screens) */}
          <NavBar />

          {/* Main Content Area */}
          <main className="flex-1 bg-gray-100 w-[87%] h-full overflow-auto ">
            <HeaderNav />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}






{/* <div className="min-h-screen flex">
    <div className="hidden lg:block w-64 bg-gray-800 text-white p-6">
      <div className="text-2xl font-bold mb-8">MyApp</div>
      <nav>
      <ul className="space-y-4">
        <li>
        <Link href="/dashboard" className="hover:text-purple-400 transition duration-300">
          Dashboard
        </Link>
        </li>
        <li>
        <Link href="/dashboard/referral" className="hover:text-purple-400 transition duration-300">
          Referral
        </Link>
        </li>
        <li>
        <Link href="/dashboard/quest" className="hover:text-purple-400 transition duration-300">
          Quest
        </Link>
        </li>
        <li>
        <Link href="/dashboard/transaction-history" className="hover:text-purple-400 transition duration-300">
          Transaction History
        </Link>
        </li>
        <li>
        <Link href="/dashboard/earnings" className="hover:text-purple-400 transition duration-300">
          Earnings
        </Link>
        </li>
      </ul>
      </nav>
    </div>

    <div className="flex-1 bg-gray-100 p-8">
      {children}
    </div>
    </div> */}
